title: Seongbin An # your name (or website title) here
logo: "/images/profile_MS3.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Study what I need.
  <br><br>
  <a href="mailto:sbin@kaist.ac.kr">E-mail</a>
  <br>
  <a href="https://scholar.google.com/citations?user=_EnZafAAAAAJ&hl=en">Google scholar</a>
  <!-- <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> -->
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
